# Generated by Django 4.2.5 on 2023-09-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa', models.CharField(max_length=100)),
                ('placar', models.CharField(max_length=10)),
                ('fora', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
