# Generated by Django 4.2.5 on 2023-10-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bbistats', '0002_time_remove_result_id_result_idresults_result_liga_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={},
        ),
    ]
